# Generated by Django 3.1.5 on 2021-03-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('password', models.CharField(default='', max_length=30)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='freelancer/images')),
            ],
            options={
                'unique_together': {('username', 'name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('clientId', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='', max_length=30)),
                ('subcategory', models.CharField(default='', max_length=30)),
                ('budget', models.IntegerField(default=0)),
                ('date_start', models.DateField()),
                ('deanline', models.DateField()),
                ('content', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
