# Generated by Django 3.1.7 on 2021-03-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210306_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publishCategory',
            field=models.CharField(default='', max_length=30),
        ),
    ]
