# Generated by Django 3.1.7 on 2021-03-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_project_publishcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='clientId',
            field=models.IntegerField(),
        ),
    ]
