# Generated by Django 3.1.7 on 2021-03-20 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210312_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('freelanceId', models.IntegerField(default=0)),
                ('projectId', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
        ),
    ]
