# Generated by Django 3.1.7 on 2021-03-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210320_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestbyclient',
            old_name='freelanceId',
            new_name='freelancerId',
        ),
    ]
