# Generated by Django 3.1.7 on 2021-03-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210320_1317'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestbyclient',
            unique_together={('client', 'projectId')},
        ),
    ]
