# Generated by Django 3.1.7 on 2021-03-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_paymet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paymet',
            new_name='payment',
        ),
    ]
