# Generated by Django 3.1.7 on 2021-03-31 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_auto_20210331_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinec',
            name='client',
        ),
        migrations.RemoveField(
            model_name='timelinec',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='timelinec',
            name='project',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='timelineC',
        ),
    ]
