# Generated by Django 3.1.7 on 2021-04-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
