# Generated by Django 3.1.7 on 2021-03-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20210320_1317'),
        ('freelancer', '0008_auto_20210318_0950'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatlits',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer')),
            ],
        ),
    ]
