# Generated by Django 3.1.7 on 2021-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatlits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlits',
            name='projectId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
