# Generated by Django 3.1.7 on 2021-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0011_auto_20210327_1326'),
        ('client', '0007_auto_20210320_1317'),
        ('chat', '0003_auto_20210323_2055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatlits',
            unique_together={('freelancer', 'projectId', 'client')},
        ),
    ]
