# Generated by Django 3.1.7 on 2021-03-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210327_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatlits',
            unique_together=set(),
        ),
    ]
