# Generated by Django 3.1.5 on 2021-03-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('email', models.CharField(default='', max_length=40)),
                ('password', models.CharField(default='', max_length=30)),
                ('rating', models.IntegerField(default=0)),
                ('levels', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=40)),
                ('sub_category', models.CharField(default='', max_length=40)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='freelancer/images')),
            ],
        ),
    ]
