# Generated by Django 3.1.5 on 2021-03-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
