# Generated by Django 3.1.5 on 2021-03-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0002_freelancer_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freelancer',
            unique_together={('username', 'name', 'email')},
        ),
    ]
