# Generated by Django 3.1.5 on 2021-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0003_auto_20210305_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(default='/static/img/dp.png', upload_to='freelancer/images'),
        ),
    ]
