# Generated by Django 3.1.5 on 2021-03-06 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0005_auto_20210306_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='gig',
            fields=[
                ('gigId', models.AutoField(primary_key=True, serialize=False)),
                ('freelancerId', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer')),
            ],
        ),
    ]
