# Generated by Django 3.1.7 on 2021-03-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0008_auto_20210318_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestByFreelancer',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('clientId', models.IntegerField(default=0)),
                ('projectId', models.IntegerField(default=0)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer')),
            ],
        ),
    ]
