# Generated by Django 3.1.7 on 2021-03-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0009_requestbyfreelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbyfreelancer',
            name='content',
            field=models.TextField(default=' '),
        ),
    ]
