# Generated by Django 3.1.7 on 2021-03-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0010_requestbyfreelancer_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestbyfreelancer',
            unique_together={('freelancer', 'projectId')},
        ),
    ]
