# Generated by Django 3.1.7 on 2021-03-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0012_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
