# Generated by Django 3.1.7 on 2021-03-31 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_timelinec'),
        ('freelancer', '0014_auto_20210331_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='timelineFC',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('flag', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freelancer.timelinefc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.project')),
            ],
        ),
        migrations.DeleteModel(
            name='timeline',
        ),
    ]
