# Generated by Django 3.1.7 on 2021-03-31 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20210331_1743'),
        ('freelancer', '0016_auto_20210331_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='files',
            new_name='trashFiles',
        ),
    ]
