# Generated by Django 3.1.7 on 2021-03-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20210331_1743'),
        ('freelancer', '0017_auto_20210331_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(default='', upload_to='freelancer/files')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancer.freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.project')),
            ],
        ),
        migrations.DeleteModel(
            name='trashFiles',
        ),
    ]
