# Generated by Django 3.1.7 on 2021-04-01 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0020_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='report',
        ),
    ]
