# Generated by Django 3.1.7 on 2021-04-01 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0022_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('freelancer', 'client')},
        ),
    ]
