# Generated by Django 3.1.7 on 2021-04-01 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer', '0023_auto_20210401_1011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
    ]
